apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ include "ebpf-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    {{ toYaml .Values.config | trim | nindent 4 }}
